### PR TITLE
Topic sender

### LINKED ISSUE #118: BUG | Wrong topic sender metadata
Should be sender's uuid and key info not the current peer

https://github.com/datapartyjs/dataparty-api/blob/5e925d4b4915e801daf599e07d69e7b866fd72af/src/topics/peer-node.js#L36

### LINKED ISSUE #120: FEAT | `LocalTopicHost.internalSubscribe`
## 🚀 Feature Proposal

Make a way for `Tasks` to subscribe to topics. There's currently a way to publish but not subscribe.

### PR DESCRIPTION
**Pull request by sevenbitbyte**
## Issues resolved:

- [x] closes #118
- [ ] closes #120 
- [x] support https://github.com/datapartyjs/dataparty-crypto/pull/45

### CODE REVIEW

File: src/comms/peer-comms.js [hunk 1]
```diff
@@ -419,9 +420,18 @@ class PeerComms extends ISocketComms {
       }
     }
     
+    debug('clienr auth op offer -', offer)
     debug('ALLOW - allowing client - ', this.remoteIdentity)
 
-    this.aesStream = await this.party.privateIdentity.recoverStream(offer, true)
+    //this.aesStream = await this.party.privateIdentity.recoverStream(offer, true)
```
Comment (sevenbitbyte) [inline src/comms/peer-comms.js]: dead code
