### PR TITLE
Topics fix secureconfig

### LINKED ISSUE #99: FEAT | Topic ACLs
## 🚀 Feature Proposal

Add support for defining topic ACLs in a service. Should be able to control the entire space of paths that are allowed and have granular control of allowed operations.

 - path
 - canAdvertise
 - canPublish
 - canSubscribe

### PR DESCRIPTION
**Pull request by sevenbitbyte**
## Issues resolved:

- [x] closes #99 
- [x] #97 
- [ ] partial #102 
- [ ] partial #103
- [x] #104 
- [x] #91 
- [x] #105 
- [x] #106

### CODE REVIEW

File: src/config/secure-config.js [hunk 1]
```diff
@@ -194,6 +197,11 @@ class SecureConfig extends IConfig {
             throw new Error('unsupported KDF['+type+']')
         }
 
+
+        debug('seed', seed)
```
Comment (sevenbitbyte) [inline src/config/secure-config.js:201]: remove debug
